---
wsl_profile: ci
execution_platform: molecule
git_default_branch: "main"
git_pull_rebase: "false"
git_core_autocrlf: "input"
git_core_filemode: "false"
git_global_excludesfile: "~/.gitignore_global"
git_user_name: ""
git_user_email: ""
