---
- name: Converge default smoke scenario
  hosts: molecule
  become: true
  vars_files:
    - ../resources/common-vars.yml
  tasks:
    - name: Gather smoke facts
      ansible.builtin.setup:
        gather_subset:
          - min
