---
- name: Converge runtime scenario
  hosts: molecule
  become: true
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/platform/molecule.yml
    - ../../group_vars/profiles/ci.yml
    - ../resources/common-vars.yml
  pre_tasks:
    - name: Prepare Ansible working directories
      include_tasks: ../../tasks/setup_download_dirs.yml
  tasks:
    - name: Apply cache role
      import_role:
        name: cache

    - name: Apply base role
      import_role:
        name: base

    - name: Apply development-runtime role
      import_role:
        name: development-runtime
