apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: learning-app
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: web-application

namespace: default