---
- name: Install development runtime components
  import_tasks: install.yml

- name: Verify development-runtime role installation
  import_tasks: validate.yml
  when: validate_installation | default(true)
