---
- name: Verify postgresql scenario
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check postgresql commands
      command: "{{ item }}"
      changed_when: false
      loop:
        - psql --version
        - pg_config --version
        - neonctl --version

    - name: Check PostgreSQL repository file
      stat:
        path: /etc/apt/sources.list.d/pgdg.list
      register: pg_repo

    - name: Assert PostgreSQL repository exists
      assert:
        that:
          - pg_repo.stat.exists
