---
- name: Verify postgresql scenario
  hosts: all
  gather_facts: false
  tasks:
    - name: Check postgresql commands
      command: "{{ item }}"
      changed_when: false
      loop:
        - psql --version
        - pg_config --version
        - neonctl --version

    - name: Check PostgreSQL repository configuration
      shell: |
        grep -R "apt.postgresql.org/pub/repos/apt" /etc/apt/sources.list /etc/apt/sources.list.d 2>/dev/null
      changed_when: false
      register: pg_repo

    - name: Assert PostgreSQL repository is configured
      assert:
        that:
          - pg_repo.rc == 0
