---
- name: Converge kubernetes-security scenario
  hosts: molecule
  become: true
  vars_files:
    - ../resources/common-vars.yml
  pre_tasks:
    - name: Prepare Ansible working directories
      include_tasks: ../../tasks/setup_download_dirs.yml
  tasks:
    - name: Apply cache role
      import_role:
        name: cache

    - name: Apply base role
      import_role:
        name: base

    - name: Apply kubernetes role
      import_role:
        name: kubernetes

    - name: Apply security role
      import_role:
        name: security
