---
- name: Converge docker scenario
  hosts: all
  become: true
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/platform/molecule.yml
    - ../../group_vars/profiles/ci.yml
    - ../resources/common-vars.yml
  vars:
    base_system_packages:
      - curl
      - apt-transport-https
      - gnupg
      - ca-certificates
      - lsb-release
  pre_tasks:
    - name: Prepare Ansible working directories
      include_tasks: ../../tasks/setup_download_dirs.yml
  tasks:
    - name: Apply base role
      import_role:
        name: base

    - name: Apply docker role
      import_role:
        name: docker
